source "https://rubygems.org"

gem "bigdecimal"
gem "builder"
gem "erbse"
gem "front_matter_parser", "~> 1.0"
gem "ostruct"
gem "dry-core", ">= 0.9"
gem "dry-monads", ">= 1.5"
gem "dry-system", ">= 0.27"
gem "dry-types", ">= 1.6"
gem "dry-view", ">= 0.8"
gem "pry"
gem "transproc"

group :development, :test do
  gem "byebug"
  gem "foreman"
  gem "guard"
  gem "guard-shell"
  gem "minitest"
  gem "rackup"
  gem "rake"
  gem "webrick"
end
