# frozen_string_literal: true

# SEO data tables for Site::View::Context — generated from the case/when
# blocks by test/scripts/build_seo_data.rb (behavior-preserving migration).
# Do not edit by hand; regenerate and re-run test/seo_snapshot_test.rb.
#
# Fallbacks: DEFAULT_TITLES -> site_name, DEFAULT_DESCRIPTIONS ->
# page_title, DEFAULT_KEYWORDS -> DEFAULT_KEYWORDS_FALLBACK.
module Site
  module View
    module SeoData
      DEFAULT_KEYWORDS_FALLBACK = "Aikido, POA, Polska Organizacja Aikido, Polish Aikido Organization, Toyoda, Germanov".freeze

      # Shared lookup: exact path in the data hash wins, then the first
      # matching pattern (template receives the MatchData), then fallback.
      def self.lookup(data, patterns, fallback, path)
        return data[path] if data.key?(path)

        patterns.each do |regex, template|
          if (match = regex.match(path.to_s))
            return template.call(match)
          end
        end

        fallback
      end
DEFAULT_TITLES = {
  "index.html" => "Treningi Aikido w Gdyni | Aikido dla początkujących | Sesshinkan Dojo POA",
  "" => "Treningi Aikido w Gdyni | Aikido dla początkujących | Sesshinkan Dojo POA",
  nil => "Treningi Aikido w Gdyni | Aikido dla początkujących | Sesshinkan Dojo POA",
  "en" => "Polish Aikido Organization | Sesshinkan Dojo Gdynia - Aikido Training",
  "en/" => "Polish Aikido Organization | Sesshinkan Dojo Gdynia - Aikido Training",
  "kontakt.html" => "Kontakt i grafik treningów Aikido | Gdynia | Sesshinkan Dojo",
  "aikido/czym_jest.html" => "Czym jest Aikido? | POA - Aikido Polska - Zasady i Filozofia",
  "aikido/historia.html" => "Historia Aikido | Od O-Sensei do wspolczesnosci | POA",
  "aikido/korzysci.html" => "Korzysci z Aikido | Zdrowie, Samoobrona, Rozwoj | POA",
  "aikido/dla_poczatkujacych.html" => "Aikido dla początkujących Gdynia | Pierwszy trening | Sesshinkan Dojo",
  "aikido/aiki_taiso.html" => "Aiki Taiso | Cwiczenia i Rozgrzewka Aikido | POA",
  "aikido/reishiki.html" => "Reishiki | Etykieta Dojo Aikido | Sesshinkan Dojo",
  "aikido/budo_zen.html" => "Budo i Zen w Aikido | Mushin, Zanshin i Bushido | POA",
  "aikido/ki_kokyu.html" => "Ki i Kokyu w Aikido | Energia i Siła Oddechu | POA",
  "slowniczek.html" => "Slowniczek Aikido | Terminy Japonskie | POA",
  "wymagania_egzaminacyjne/kyu.html" => "Wymagania Kyu | Stopnie Poczatkujace Aikido | POA",
  "wymagania_egzaminacyjne/dan.html" => "Wymagania Dan | Czarne Pasy Aikido | POA",
  "lineage.html" => "Linia Przekazu Aikido | Ueshiba, Toyoda, Germanov | POA",
  "biografie/o-sensei.html" => "Morihei Ueshiba O-Sensei | Tworca Aikido | Biografia",
  "biografie/kisshomaru.html" => "Kisshomaru Ueshiba | Drugi Doshu Aikido | Biografia",
  "biografie/moriteru.html" => "Moriteru Ueshiba | Trzeci Doshu Aikido | Biografia",
  "biografie/mitsuteru.html" => "Mitsuteru Ueshiba | Waka Sensei | Przyszly Doshu",
  "biografie/toyoda.html" => "Fumio Toyoda Shihan | Kluczowa Postac POA | Biografia",
  "biografie/germanov.html" => "Edward Germanov Shihan | 7 Dan | Prezes BAA",
  "biografie/ostrowski.html" => "Jacek Ostrowski | Zalozyciel POA | Wspomnienie",
  "biografie/szrajer.html" => "Oskar Szrajer | 5 Dan | Lider POA Gdynia",
  "wydarzenia/2026.html" => "Wydarzenia Aikido 2026 | Seminaria i Szkolenia | POA",
  "faq.html" => "FAQ Aikido Gdynia | Pytania o treningi i pierwszy trening | POA",
  "gdynia.html" => "Treningi Aikido w Gdyni | Grafik, lokalizacja i pierwszy trening | Sesshinkan Dojo",
  "treningi-aikido-gdynia.html" => "Treningi Aikido w Gdyni | Wieczorne zajęcia dla dorosłych | Sesshinkan Dojo",
  "pierwszy-trening-aikido-gdynia.html" => "Pierwszy trening Aikido Gdynia | Co zabrać i jak zacząć | Sesshinkan Dojo",
  "aikido-dla-doroslych-gdynia.html" => "Aikido dla dorosłych Gdynia | Wieczorne treningi | Sesshinkan Dojo",
  "yudansha.html" => "Yudansha | Czarne Pasy POA | Instruktorzy Aikido",
  "en/contact.html" => "Contact | Aikido Gdynia | Sesshinkan Dojo - Training Schedule",
  "en/aikido/what_is.html" => "What is Aikido? | POA - Polish Aikido Organization - Principles",
  "en/aikido/history.html" => "History of Aikido | From O-Sensei to Present | POA",
  "en/aikido/benefits.html" => "Benefits of Aikido | Health, Self-Defense, Development | POA",
  "en/aikido/beginners.html" => "Aikido for Beginners | First Class | Sesshinkan Dojo",
  "en/aikido/aiki_taiso.html" => "Aiki Taiso | Exercises and Warm-up | Aikido POA",
  "en/aikido/reishiki.html" => "Reishiki | Dojo Etiquette | Sesshinkan Dojo",
  "en/aikido/budo_zen.html" => "Budo and Zen in Aikido | Mushin, Zanshin, Bushido | POA",
  "en/aikido/ki_kokyu.html" => "Ki and Kokyu in Aikido | Energy and Breath Power | POA",
  "en/glossary.html" => "Aikido Glossary | Japanese Terms | POA",
  "en/requirements/kyu.html" => "Kyu Requirements | Beginner Ranks Aikido | POA",
  "en/requirements/dan.html" => "Dan Requirements | Black Belt Aikido | POA",
  "en/lineage.html" => "Aikido Lineage | Ueshiba, Toyoda, Germanov | POA",
  "en/biographies/o-sensei.html" => "Morihei Ueshiba O-Sensei | Founder of Aikido | Biography",
  "en/biographies/kisshomaru.html" => "Kisshomaru Ueshiba | Second Doshu Aikido | Biography",
  "en/biographies/moriteru.html" => "Moriteru Ueshiba | Third Doshu Aikido | Biography",
  "en/biographies/mitsuteru.html" => "Mitsuteru Ueshiba | Waka Sensei | Future Doshu",
  "en/biographies/toyoda.html" => "Fumio Toyoda Shihan | Key Figure POA | Biography",
  "en/biographies/germanov.html" => "Edward Germanov Shihan | 7th Dan | BAA President",
  "en/biographies/ostrowski.html" => "Jacek Ostrowski | POA Founder | Memorial",
  "en/biographies/szrajer.html" => "Oskar Szrajer | 5th Dan | POA Head Gdynia",
  "en/events/2026.html" => "Aikido Events 2026 | Seminars and Workshops | POA",
  "en/faq.html" => "FAQ | Frequently Asked Questions | Aikido POA",
  "en/gdynia.html" => "Aikido Gdynia | Sesshinkan Dojo | Tri-City Training",
  "en/yudansha.html" => "Yudansha | POA Black Belts | Aikido Instructors",
  "blog.html" => "Blog | Polska Organizacja Aikido",
  "blog/bushido-droga-wojownika.html" => "Bushido — droga wojownika w praktyce dojo | Blog",
  "blog/kaizen-ciagle-doskonalenie.html" => "Kaizen — ciągłe doskonalenie w Aikido | Blog",
  "blog/gaman-wytrwalosc.html" => "Gaman — wytrwałość i opanowanie na macie | Blog",
  "blog/kintsugi-zlota-naprawa.html" => "Kintsugi — złota naprawa i odporność psychiczna | Blog",
  "blog/wabi-sabi-piekno-niedoskonalosci.html" => "Wabi-sabi — piękno niedoskonałości w treningu | Blog",
  "blog/mushin-umysl-bez-umyslu.html" => "Mushin — umysł bez umysłu w Aikido | Blog",
  "blog/sesshin-gleboka-praktyka.html" => "Sesshin — głęboka praktyka i tożsamość Sesshinkan Dojo | Blog",
  "blog/zenshin-pelne-zaangazowanie.html" => "Zenshin — pełne zaangażowanie w każdym ruchu | Blog",
  "blog/zanshin-czujnosc-po-technice.html" => "Zanshin — czujność po technice i domknięcie działania | Blog",
  "blog/enso-krag-obecnosci.html" => "Ensō — krąg obecności i trening decyzji | Blog",
  "blog/hyoshi-rytm-timing-jednosci-ruchu.html" => "Hyōshi — rytm i timing jedności w Aikido | Blog",
  "blog/fudoshin-niewzruszony-umysl.html" => "Fudōshin — niewzruszony umysł i stabilność pod presją | Blog",
  "blog/shoshin-umysl-poczatkujacego.html" => "Shoshin — umysł początkującego i pokora w rozwoju | Blog",
  "blog/shuhari-etapy-dojrzewania-w-treningu.html" => "Shuhari — etapy dojrzewania w treningu i droga do swobody | Blog",
  "blog/hansei-uczciwa-autorefleksja-bez-wymowek.html" => "Hansei — uczciwa autorefleksja bez wymówek i korekta ego | Blog",
  "blog/aiki-harmonia-w-dzialaniu.html" => "Aiki — harmonia w działaniu, nie w deklaracji | Blog",
  "blog/wa-harmonia-bez-uleglosci.html" => "Wa — harmonia bez uległości i porządek relacji | Blog",
  "blog/giri-obowiazek-bez-wymowek.html" => "Giri — obowiązek bez wymówek i odpowiedzialność w dojo | Blog",
  "blog/droga-i-mistrzostwo.html" => "Droga i mistrzostwo — kiedy technika przestaje wystarczać | Blog",
  "blog/ikigai-sens-regularnej-praktyki.html" => "Ikigai — sens, który wytrzymuje zwykły tydzień | Blog",
  "blog/mottainai-nie-marnuj-tego-co-moze-cie-nauczyc.html" => "Mottainai — nie marnuj tego, z czego możesz się uczyć | Blog",
  "blog/mono-no-aware-czulosc-wobec-przemijania.html" => "Mono no aware — czułość wobec przemijania, która porządkuje praktykę | Blog",
  "blog/ikkyo-pierwsza-nauka-ktora-nie-konczy-sie-nigdy.html" => "Ikkyo — pierwsza nauka, która nie kończy się nigdy | Blog",
  "blog/yugen-glebia-ktorej-nie-da-sie-splaszczyc.html" => "Yūgen — głębia, której nie da się spłaszczyć do instrukcji | Blog",
  "blog/egzamin-w-budo-pokaz-drogi-nie-wystep.html" => "Egzamin w budō — pokaz drogi, nie występ przed komisją | Blog",
  "blog/ukemi-bezpiecznie-upasc-zachowac-strukture-wrocic-do-dzialania.html" => "Ukemi — jak bezpiecznie upadać i wracać do działania | Blog",
  "blog/genkikai-cialo-ktore-wraca-na-miejsce.html" => "Genkikai — ciało, które wraca na miejsce | Blog",
  "blog/inna-sciezka-na-ten-sam-szczyt.html" => "Inna ścieżka na ten sam szczyt — budō wobec zmian i przeciwności | Blog",
  "blog/ninjo-ludzkie-uczucia-bez-utraty-kierunku.html" => "Ninjō — ludzkie uczucia bez utraty kierunku | Blog",
  "blog/omotenashi-goscinnosc-ktora-buduje-dojo.html" => "Omotenashi — gościnność, która buduje dojo | Blog",
  "blog/nemawashi-przygotowanie-gruntu-przed-dzialaniem.html" => "Nemawashi — przygotowanie gruntu przed działaniem | Blog",
  "blog/misogi-oczyszczenie-przez-praktyke.html" => "Misogi — oczyszczenie przez praktykę, nie przez pozę | Blog",
  "blog/5-zasad-kazdej-techniki.html" => "5 zasad każdej techniki — centrum, oś, timing, wybranie luzu, kuzushi | Blog",
  "blog/dlaczego-w-aikido-nosi-sie-hakame.html" => "Dlaczego w aikido nosi się hakamę? Heifuku, ruch i sens tradycji | Blog",
  "blog/dla-kogo-jest-aikido.html" => "Dla kogo jest aikido? Początkujący, dorośli i osoby po przerwie | Blog",
  "blog/czy-warto-cwiczyc-aikido.html" => "Czy warto ćwiczyć aikido? Korzyści, ograniczenia i sens treningu | Blog",
  "blog/aikido-w-kazdym-wieku.html" => "Aikido w każdym wieku? Jak zacząć rozsądnie niezależnie od wieku | Blog",
  "blog/aikido-dla-nastolatkow.html" => "Aikido dla nastolatków? Dyscyplina, sprawność i rozwój bez sportowej presji | Blog",
  "blog/ichi-go-ichi-e-kazde-spotkanie-zdarza-sie-tylko-raz.html" => "Ichi-go ichi-e — każde spotkanie zdarza się tylko raz | Blog",
  "blog/jeden-nauczyciel-jeden-przekaz.html" => "Jeden nauczyciel, jeden przekaz — porządek nauki w dojo i na seminarium | Blog",
  "blog/styl-aikido-fumio-toyody-technika-i-zen.html" => "Styl Aikido Fumio Toyody — technika i Zen jako jeden system | Blog",
  "blog/linia-toyoda-germanov-jak-cwiczymy.html" => "Linia Toyoda–Germanov — jak ćwiczymy i czym wyróżnia się nasza szkoła | Blog",
  "blog/omoiyari-uwazna-troska.html" => "Omoiyari — uważna troska i odpowiedzialny partnering | Blog",
  "blog/jiko-sekinin-odpowiedzialnosc-osobista.html" => "Jiko sekinin — odpowiedzialność osobista w dojo | Blog",
  "blog/kuzushi-kontrolowana-nierownowaga.html" => "Kuzushi — kontrolowana nierównowaga i prowadzenie techniki | Blog",
  "en/blog.html" => "Blog | Polish Aikido Organization",
  "en/blog/bushido-way-of-the-warrior.html" => "Bushido — the warrior's way in dojo practice | Blog",
  "en/blog/kaizen-continuous-improvement.html" => "Kaizen — continuous improvement in Aikido training | Blog",
  "en/blog/gaman-endurance-and-composure.html" => "Gaman — endurance and composure on the mat | Blog",
  "en/blog/kintsugi-golden-repair.html" => "Kintsugi — golden repair and resilient mindset | Blog",
  "en/blog/wabi-sabi-beauty-of-imperfection.html" => "Wabi-sabi — beauty of imperfection in practice | Blog",
  "en/blog/mushin-no-mind.html" => "Mushin — no-mind state in Aikido practice | Blog",
  "en/blog/sesshin-deep-practice.html" => "Sesshin — deep practice and Sesshinkan Dojo identity | Blog",
  "en/blog/zenshin-full-commitment.html" => "Zenshin — full commitment in every movement | Blog",
  "en/blog/zanshin-awareness-after-execution.html" => "Zanshin — awareness after execution and process closure | Blog",
  "en/blog/enso-circle-of-presence.html" => "Ensō — circle of presence and decision training | Blog",
  "en/blog/hyoshi-timing-reveals-unity-of-movement.html" => "Hyōshi — rhythm and timing of unity in Aikido | Blog",
  "en/blog/fudoshin-immovable-mind.html" => "Fudōshin — immovable mind and stability under pressure | Blog",
  "en/blog/shoshin-beginners-mind.html" => "Shoshin — beginner's mind and humility in growth | Blog",
  "en/blog/shuhari-stages-of-maturation-in-training.html" => "Shuhari — stages of maturation in training and the path to freedom | Blog",
  "en/blog/hansei-honest-self-reflection-without-excuses.html" => "Hansei — honest self-reflection without excuses and ego defense | Blog",
  "en/blog/aiki-harmony-in-action.html" => "Aiki — harmony in action, not in slogans | Blog",
  "en/blog/wa-harmony-without-submission.html" => "Wa — harmony without submission and ordered relationship | Blog",
  "en/blog/giri-duty-without-excuses.html" => "Giri — duty without excuses and responsibility in the dojo | Blog",
  "en/blog/the-path-and-mastery.html" => "The Path and Mastery — when technique is no longer enough | Blog",
  "en/blog/ikigai-the-reason-to-return-to-practice.html" => "Ikigai — meaning that survives an ordinary week | Blog",
  "en/blog/mottainai-do-not-waste-what-can-teach-you.html" => "Mottainai — do not waste what can teach you | Blog",
  "en/blog/mono-no-aware-sensitivity-to-impermanence.html" => "Mono no aware — sensitivity to impermanence that sharpens practice | Blog",
  "en/blog/ikkyo-the-first-teaching-that-never-ends.html" => "Ikkyo — the first teaching that never ends | Blog",
  "en/blog/yugen-depth-that-cannot-be-flattened.html" => "Yūgen — depth that cannot be flattened into instruction | Blog",
  "en/blog/exams-in-budo-showing-the-road-not-performing.html" => "Exams in Budō — showing the road, not performing for the panel | Blog",
  "en/blog/ukemi-falling-safely-keeping-structure-returning-to-action.html" => "Ukemi — falling safely, keeping structure, returning to action | Blog",
  "en/blog/genkikai-the-body-that-returns-to-order.html" => "Genkikai — the body that returns to order | Blog",
  "en/blog/another-path-to-the-same-summit.html" => "Another path to the same summit — budō amid change and adversity | Blog",
  "en/blog/ninjo-human-feeling-without-losing-direction.html" => "Ninjō — human feeling without losing direction | Blog",
  "en/blog/omotenashi-hospitality-that-builds-the-dojo.html" => "Omotenashi — hospitality that builds the dojo | Blog",
  "en/blog/nemawashi-laying-groundwork-before-action.html" => "Nemawashi — laying the groundwork before action | Blog",
  "en/blog/misogi-purification-through-practice.html" => "Misogi — purification through practice, not posture | Blog",
  "en/blog/five-principles-behind-every-technique.html" => "Five principles behind every technique — center, axis, timing, slack removal, kuzushi | Blog",
  "en/blog/why-aikido-practitioners-wear-hakama.html" => "Why do Aikido practitioners wear hakama? Heifuku, movement, and tradition | Blog",
  "en/blog/who-is-aikido-for.html" => "Who is Aikido for? Beginners, adults, and returning practitioners | Blog",
  "en/blog/is-aikido-worth-practicing.html" => "Is Aikido worth practicing? Benefits, limits, and honest expectations | Blog",
  "en/blog/aikido-at-every-age.html" => "Aikido at every age? How to begin intelligently at different stages of life | Blog",
  "en/blog/aikido-for-teenagers.html" => "Aikido for teenagers? Discipline, fitness, and development without sport pressure | Blog",
  "en/blog/ichi-go-ichi-e-every-encounter-happens-only-once.html" => "Ichi-go ichi-e — every encounter happens only once | Blog",
  "en/blog/one-teacher-one-transmission.html" => "One teacher, one transmission — order in dojo and seminar learning | Blog",
  "en/blog/toyoda-aikido-style-technique-and-zen.html" => "Fumio Toyoda’s Aikido style — technique and Zen as one system | Blog",
  "en/blog/toyoda-germanov-lineage-how-we-train.html" => "Toyoda–Germanov lineage — how we train and what sets our school apart | Blog",
  "en/blog/omoiyari-considerate-compassion.html" => "Omoiyari — considerate compassion in partner work | Blog",
  "en/blog/jiko-sekinin-personal-responsibility.html" => "Jiko sekinin — personal responsibility in the dojo | Blog",
  "en/blog/kuzushi-controlled-imbalance.html" => "Kuzushi — controlled imbalance and technical guidance | Blog",
}.freeze

DEFAULT_TITLES_PATTERNS = [
  [/\Ablog-(\d+)\.html\z/, ->(match) { "Blog — strona #{match[1]} | Polska Organizacja Aikido" }],
  [/\Aen\/blog-(\d+)\.html\z/, ->(match) { "Blog — page #{match[1]} | Polish Aikido Organization" }],
].freeze


DEFAULT_DESCRIPTIONS = {
  "index.html" => "Treningi Aikido w Gdyni i Trójmieście dla początkujących oraz zaawansowanych. Sesshinkan Dojo Gdynia: wieczorne zajęcia dla dorosłych, pierwszy trening gratis, tradycyjna linia Shihan Fumio Toyody.",
  "" => "Treningi Aikido w Gdyni i Trójmieście dla początkujących oraz zaawansowanych. Sesshinkan Dojo Gdynia: wieczorne zajęcia dla dorosłych, pierwszy trening gratis, tradycyjna linia Shihan Fumio Toyody.",
  nil => "Treningi Aikido w Gdyni i Trójmieście dla początkujących oraz zaawansowanych. Sesshinkan Dojo Gdynia: wieczorne zajęcia dla dorosłych, pierwszy trening gratis, tradycyjna linia Shihan Fumio Toyody.",
  "en" => "Polish Aikido Organization following Shihan Fumio Toyoda's lineage. Sesshinkan Dojo Gdynia - Aikido training in Tri-City area. Modern approach to traditional martial art.",
  "en/" => "Polish Aikido Organization following Shihan Fumio Toyoda's lineage. Sesshinkan Dojo Gdynia - Aikido training in Tri-City area. Modern approach to traditional martial art.",
  "kontakt.html" => "Kontakt, grafik i lokalizacja treningów Aikido w Gdyni. Sprawdź adres dojo, telefon, e-mail, godziny zajęć, dojazd oraz informacje o pierwszym treningu w Sesshinkan Dojo Gdynia.",
  "aikido/czym_jest.html" => "Czym jest Aikido - japonska sztuka walki oparta na harmonii, dzwigniach i rzutach. Zasady, filozofia i rozwoj osobisty.",
  "aikido/historia.html" => "Historia Aikido od O-Sensei Morihei Ueshiby do wspolczesnosci. Rozwoj sztuki walki i jej rozprzestrzenienie.",
  "aikido/korzysci.html" => "Korzysci z treningu Aikido: sprawnosc, koncentracja, redukcja stresu, samoobrona i rozwoj osobisty.",
  "aikido/dla_poczatkujacych.html" => "Aikido dla początkujących w Gdyni: jak wyglądają zajęcia dla dorosłych, co zabrać na pierwszy trening, czego się spodziewać i jak zacząć w Sesshinkan Dojo.",
  "aikido/aiki_taiso.html" => "Aiki Taiso - cwiczenia i rozgrzewka Aikido. Ruch, koordynacja i przygotowanie ciala do treningu.",
  "aikido/reishiki.html" => "Reishiki - etykieta dojo Aikido: uklony, zachowanie, szacunek i tradycyjne zasady.",
  "aikido/budo_zen.html" => "Budo i Zen w Aikido: Mushin, Zanshin, Fudoshin oraz cnoty wojownika. Filozofia i etyka praktyki dojo.",
  "aikido/ki_kokyu.html" => "Ki i Kokyu w Aikido: energia życiowa, siła oddechu i praca z centrum. Poznaj pojęcia Ki, Kokyu-ryoku oraz praktykę oddechu.",
  "slowniczek.html" => "Slowniczek terminow Aikido z tlumaczeniami japonskich nazw technik i pojec.",
  "wymagania_egzaminacyjne/kyu.html" => "Wymagania egzaminacyjne Aikido na stopnie Kyu od 6 kyu do 1 kyu. Lista technik i zasad.",
  "wymagania_egzaminacyjne/dan.html" => "Wymagania egzaminacyjne Aikido na stopnie Dan od Shodan wzwyz. Techniki i kryteria.",
  "lineage.html" => "Linia przekazu Aikido od O-Sensei przez rodzine Ueshiba, Shihana Toyode i Germanova do POA.",
  "biografie/o-sensei.html" => "Morihei Ueshiba O-Sensei - tworca Aikido. Zyciorys i idea sztuki opartej na harmonii.",
  "biografie/kisshomaru.html" => "Kisshomaru Ueshiba - drugi Doshu Aikido. Rola w rozwoju i upowszechnieniu Aikido.",
  "biografie/moriteru.html" => "Moriteru Ueshiba - trzeci Doshu Aikido. Przywodztwo Aikikai i wspolczesne Aikido.",
  "biografie/mitsuteru.html" => "Mitsuteru Ueshiba - Waka Sensei, przyszly czwarty Doshu. Kontynuacja linii Ueshiba.",
  "biografie/toyoda.html" => "Shihan Fumio Toyoda - wybitny nauczyciel Aikido i kluczowa postac linii POA.",
  "biografie/germanov.html" => "Shihan Edward Germanov - 7 dan, prezes BAA i Tendokan. Rozwoj Aikido w Europie.",
  "biografie/ostrowski.html" => "Sensei Jacek Ostrowski - zalozyciel Polskiej Organizacji Aikido. Wspomnienie nauczyciela.",
  "biografie/szrajer.html" => "Sensei Oskar Szrajer - 5 dan, obecny lider POA i instruktor w Gdyni.",
  "wydarzenia/2026.html" => "Wydarzenia Aikido 2026: seminaria, szkolenia, egzaminy i terminy spotkan POA.",
  "faq.html" => "FAQ o Aikido w Gdyni: odpowiedzi o pierwszym treningu, kosztach, stroju, grafiku, lokalizacji dojo i rozpoczęciu zajęć w Sesshinkan Dojo.",
  "gdynia.html" => "Treningi Aikido w Gdyni w Sesshinkan Dojo: grafik zajęć, lokalizacja dojo, pierwszy trening gratis, instruktor oraz praktyczne informacje dla początkujących i dorosłych.",
  "treningi-aikido-gdynia.html" => "Treningi Aikido w Gdyni dla dorosłych i początkujących: grafik, miejsce zajęć, przebieg treningu i praktyczne informacje o starcie w Sesshinkan Dojo.",
  "pierwszy-trening-aikido-gdynia.html" => "Pierwszy trening Aikido w Gdyni krok po kroku: co zabrać, jak wygląda wejście na matę, czy można zacząć bez doświadczenia i jak przygotować się do zajęć.",
  "aikido-dla-doroslych-gdynia.html" => "Aikido dla dorosłych w Gdyni: wieczorne treningi dla osób początkujących i pracujących. Sprawdź, dla kogo są zajęcia i jak zacząć w Sesshinkan Dojo.",
  "en/contact.html" => "Contact Polish Aikido Organization and Sesshinkan Dojo Gdynia. Address, phone, email, training schedule, and organization details.",
  "en/aikido/what_is.html" => "Aikido is a Japanese martial art based on harmony, locks, throws, and strikes. Learn about the Four Fundamental Principles, Ki energy, and the path of self-improvement through Aikido training.",
  "en/aikido/history.html" => "History of Aikido from O-Sensei Morihei Ueshiba to modern times. Learn about the development of this Japanese martial art and its spread worldwide.",
  "en/aikido/benefits.html" => "Benefits of Aikido training: physical fitness, mental focus, stress reduction, self-defense skills, and personal development through martial arts practice.",
  "en/aikido/beginners.html" => "Complete guide for Aikido beginners: what to expect, how to prepare, training structure, basic techniques, and etiquette for your first classes.",
  "en/aikido/aiki_taiso.html" => "Aiki Taiso - basic Aikido exercises and warm-up movements. Learn fundamental exercises that prepare body and mind for Aikido practice.",
  "en/aikido/reishiki.html" => "Reishiki - Aikido dojo etiquette and ceremonial practices. Essential guide to respect, bowing, behavior, and traditional customs in Aikido training.",
  "en/aikido/budo_zen.html" => "Budo and Zen in Aikido: Mushin, Zanshin, Fudoshin and the seven samurai virtues. Philosophy and ethics of dojo practice.",
  "en/aikido/ki_kokyu.html" => "Ki and Kokyu in Aikido: life energy, breath power, and working from the center. Learn about Ki, Kokyu-ryoku, and breath training.",
  "en/glossary.html" => "Complete Aikido glossary with Japanese terms, techniques, ranks, and philosophical concepts. Essential reference for practitioners.",
  "en/requirements/kyu.html" => "Aikido Kyu rank examination requirements from 6th Kyu to 1st Kyu. Detailed list of techniques and knowledge required for colored belt tests.",
  "en/requirements/dan.html" => "Aikido Dan rank examination requirements from Shodan to Yondan. Black belt techniques, principles, and mastery expectations for advanced practitioners.",
  "en/biographies/o-sensei.html" => "Morihei Ueshiba O-Sensei - founder of Aikido. Biography of the master who created this martial art based on harmony and spiritual principles.",
  "en/biographies/kisshomaru.html" => "Kisshomaru Ueshiba - second Doshu and son of O-Sensei. His role in spreading Aikido worldwide and systematizing the art.",
  "en/biographies/moriteru.html" => "Moriteru Ueshiba - third and current Doshu of Aikido. Leading the international Aikido community and preserving O-Sensei's legacy.",
  "en/biographies/mitsuteru.html" => "Mitsuteru Ueshiba - Waka Sensei and future fourth Doshu. Grandson of the current Doshu, continuing the Ueshiba family lineage.",
  "en/biographies/toyoda.html" => "Shihan Fumio Toyoda - influential Aikido master who brought the art to America. Founder of AAA and our lineage's key teacher.",
  "en/biographies/germanov.html" => "Shihan Edward Germanov - 7th dan, President of Baltic Aikido Association and Tendokan. Key figure in European Aikido development.",
  "en/biographies/ostrowski.html" => "Sensei Jacek Ostrowski - founder of Polish Aikido Organization (POA). Memorial to a dedicated teacher who shaped Polish Aikido.",
  "en/biographies/szrajer.html" => "Sensei Oskar Szrajer - 5th dan, current head of Polish Aikido Organization. Leading POA's development and training in Gdynia.",
  "en/lineage.html" => "Aikido lineage from O-Sensei Morihei Ueshiba through the Ueshiba family, Shihan Toyoda, Shihan Germanov to Polish Aikido Organization.",
  "en/events/2026.html" => "Aikido events and training seminars in 2026. Schedule of workshops, examinations, and special training sessions organized by POA.",
  "yudansha.html" => "Lista 24 czarnych pasów (yudansha) Polskiej Organizacji Aikido - instruktorzy z rangą od Shodan (1 Dan) do Godan (5 Dan). Wszyscy wyegzaminowani w linii Shihan Fumio Toyoda.",
  "en/yudansha.html" => "List of 24 black belts (yudansha) from Polish Aikido Organization - instructors ranked from Shodan (1st Dan) to Godan (5th Dan). All examined in Shihan Fumio Toyoda's lineage.",
  "blog.html" => "Blog POA: relacje ze staży, komunikaty dojo, zapowiedzi wydarzeń i informacje dla ćwiczących Aikido.",
  "blog/bushido-droga-wojownika.html" => "Bushido w praktyce Aikido: dyscyplina, odpowiedzialność i etyka pracy w dojo, które budują trwałe umiejętności.",
  "blog/kaizen-ciagle-doskonalenie.html" => "Kaizen w treningu Aikido: małe, konsekwentne kroki, które przekładają się na realny postęp techniczny i mentalny.",
  "blog/gaman-wytrwalosc.html" => "Gaman jako fundament praktyki: wytrwałość, opanowanie i jakość decyzji pod presją na macie i poza nią.",
  "blog/kintsugi-zlota-naprawa.html" => "Kintsugi jako metafora rozwoju aikidoki: jak błędy, korekta i konsekwencja wzmacniają technikę oraz charakter.",
  "blog/wabi-sabi-piekno-niedoskonalosci.html" => "Wabi-sabi w Aikido: akceptacja niedoskonałości, praca nad detalem i dojrzewanie techniki przez regularny trening.",
  "blog/mushin-umysl-bez-umyslu.html" => "Mushin w praktyce: jak budować swobodną, nieusztywnioną reakcję i utrzymywać klarowność działania w technice.",
  "blog/sesshin-gleboka-praktyka.html" => "Sesshin jako głęboka praktyka Aikido: koncentracja, dyscyplina i standard pracy, który definiuje Sesshinkan Dojo.",
  "blog/zenshin-pelne-zaangazowanie.html" => "Zenshin, czyli pełne zaangażowanie ciała i umysłu w ruchu, kontakt z partnerem i finalizację techniki.",
  "blog/zanshin-czujnosc-po-technice.html" => "Zanshin jako pozostająca czujność po wykonaniu techniki: jak domykać działanie i utrzymywać jakość pod presją.",
  "blog/enso-krag-obecnosci.html" => "Ensō w praktyce Aikido i zen: jeden ruch, który odsłania jakość obecności, decyzji i domknięcia działania.",
  "blog/hyoshi-rytm-timing-jednosci-ruchu.html" => "Hyōshi w Aikido i budō: jak timing ujawnia jedność decyzji, oddechu i ruchu oraz dlaczego spóźnienie niszczy technikę.",
  "blog/fudoshin-niewzruszony-umysl.html" => "Fudōshin w Aikido i budō: niewzruszony umysł jako praktyczna stabilność decyzji, oddechu i postawy pod presją.",
  "blog/shoshin-umysl-poczatkujacego.html" => "Shoshin w Aikido i budō: jak umysł początkującego chroni przed rutyną, pychą i techniczną stagnacją.",
  "blog/shuhari-etapy-dojrzewania-w-treningu.html" => "Shuhari w Aikido i budō: jak wiernie przepracowana forma dojrzewa w zrozumienie i swobodę, zamiast rozpadać się w chaos lub ego.",
  "blog/hansei-uczciwa-autorefleksja-bez-wymowek.html" => "Hansei w Aikido i budō: jak uczciwa autorefleksja bez wymówek pozwala zobaczyć własny błąd, przyjąć korektę i naprawdę dojrzewać w treningu.",
  "blog/aiki-harmonia-w-dzialaniu.html" => "Aiki w Aikido: jak przejąć timing, dystans i balans ataku bez zderzania siły z siłą oraz dlaczego ta zasada zaczyna się jeszcze przed techniką.",
  "blog/wa-harmonia-bez-uleglosci.html" => "Wa w Aikido i budō: harmonia bez uległości, czyli jak utrzymać porządek relacji, korekty i wspólnej praktyki pod presją.",
  "blog/giri-obowiazek-bez-wymowek.html" => "Giri w Aikido i budō: obowiązek bez wymówek jako odpowiedzialność za partnera, korektę, linię przekazu i wspólny porządek dojo.",
  "blog/droga-i-mistrzostwo.html" => "Droga i mistrzostwo w budō: jak opanowanie technik odsłania właściwe pytania, dlaczego mistrz mówi 'nic nie wiem' i co zmienia stabilność bez zamykania się — w dojo i poza nim.",
  "blog/ikigai-sens-regularnej-praktyki.html" => "Ikigai w Aikido i budō: dlaczego sens regularnej praktyki nie jest wielkim olśnieniem, tylko czymś, co sprawdza się w powrocie na matę w zwykłym tygodniu.",
  "blog/mottainai-nie-marnuj-tego-co-moze-cie-nauczyc.html" => "Mottainai w Aikido i budō: jak rozpoznawać wartość korekty, błędu, partnera i powtórzenia, zanim zostaną zmarnowane, i zamieniać otrzymany sygnał w realną zmianę.",
  "blog/mono-no-aware-czulosc-wobec-przemijania.html" => "Mono no aware w Aikido i budō: jak świadomość przemijania wyostrza uwagę, porządkuje pracę z partnerem i pomaga podejmować decyzje, zamiast odkładać praktykę na później.",
  "blog/ikkyo-pierwsza-nauka-ktora-nie-konczy-sie-nigdy.html" => "Ikkyo w Aikido i budō: dlaczego pierwsza nauka pozostaje testem postawy, centrum, oddechu, riai i prowadzenia bez siłowania się przez całe życie praktyki.",
  "blog/yugen-glebia-ktorej-nie-da-sie-splaszczyc.html" => "Yūgen w Aikido i budō: jak rozumieć głębię techniki, której nie widać w samej instrukcji — wyczucie czasu, dystans, intencję, ciszę i kontakt z partnerem.",
  "blog/egzamin-w-budo-pokaz-drogi-nie-wystep.html" => "Egzamin w budō i aikido jako uczciwy sprawdzian drogi, przygotowania i odpowiedzialności — nie występ przed komisją ani sąd nad wartością człowieka.",
  "blog/ukemi-bezpiecznie-upasc-zachowac-strukture-wrocic-do-dzialania.html" => "Ukemi w aikido to sztuka bezpiecznego padania: jak chronić ciało, nie tracić oddechu i wracać do działania w dojo oraz poza nim.",
  "blog/genkikai-cialo-ktore-wraca-na-miejsce.html" => "Genkikai w systemie Masatomiego Ikedy: trzecia praktyka Sanshinkai, która daje ciału metodę powrotu po intensywnym treningu aikido i Hojo.",
  "blog/inna-sciezka-na-ten-sam-szczyt.html" => "Budō wobec zmian, kontuzji, utraty dawnego rytmu, pracy, relacji i codziennych przeciwności: jak nie mylić końca jednej ścieżki z końcem Drogi.",
  "blog/ninjo-ludzkie-uczucia-bez-utraty-kierunku.html" => "Ninjō w Aikido i budō: jak rozpoznawać ludzkie uczucia, nie wypierać emocji i nie pozwalać, by nastrój prowadził trening zamiast odpowiedzialności.",
  "blog/omotenashi-goscinnosc-ktora-buduje-dojo.html" => "Omotenashi w Aikido i budō: jak jakość ataku, sposób przyjmowania korekty i stosunek do mniej zaawansowanego partnera tworzą kulturę dojo od środka.",
  "blog/nemawashi-przygotowanie-gruntu-przed-dzialaniem.html" => "Nemawashi w Aikido i budō: dlaczego dobra technika, korekta i rozwój dojo wymagają przygotowania gruntu przed widocznym działaniem.",
  "blog/misogi-oczyszczenie-przez-praktyke.html" => "Misogi w Aikido i budō: jak praktyka oczyszczania oddechu, uwagi i intencji wzmacnia technikę w stylu Toyody oraz pozostaje żywa w linii przekazu.",
  "blog/5-zasad-kazdej-techniki.html" => "5 zasad każdej techniki w Aikido: praktyczny model pracy z centrum, osią, timingiem, wybraniem luzu i kuzushi oraz podzasadami, które porządkują ruch.",
  "blog/dlaczego-w-aikido-nosi-sie-hakame.html" => "Dlaczego w aikido nosi się hakamę: historyczny sens stroju, związek z heifuku, wpływ na jakość ruchu oraz symbolika siedmiu plis i siedmiu cnót.",
  "blog/dla-kogo-jest-aikido.html" => "Dla kogo jest aikido naprawdę: dla początkujących, dorosłych, osób po przerwie i tych, którzy szukają regularnej praktyki bez sportowej rywalizacji.",
  "blog/czy-warto-cwiczyc-aikido.html" => "Czy warto ćwiczyć aikido? Uczciwa odpowiedź o korzyściach, ograniczeniach i tym, dla kogo ta droga ma realny sens.",
  "blog/aikido-w-kazdym-wieku.html" => "Aikido w każdym wieku: jak zacząć trening rozsądnie mając 20, 40 albo 60 lat i od czego naprawdę zależy bezpieczny rozwój.",
  "blog/aikido-dla-nastolatkow.html" => "Aikido dla nastolatków jako droga rozwoju: dyscyplina, sprawność, samokontrola, relacje i międzynarodowe doświadczenia bez obsesji wyniku sportowego.",
  "blog/ichi-go-ichi-e-kazde-spotkanie-zdarza-sie-tylko-raz.html" => "Ichi-go ichi-e w Aikido i budō: dlaczego każde spotkanie, trening i korekta zdarzają się tylko raz i wymagają pełnej obecności zamiast rutyny.",
  "blog/jeden-nauczyciel-jeden-przekaz.html" => "Jeden nauczyciel i jeden spójny przekaz chronią ucznia przed chaosem, a starszy uczeń najlepiej wspiera naukę jako dobry uke.",
  "blog/styl-aikido-fumio-toyody-technika-i-zen.html" => "Czym wyróżnia się styl Aikido Fumio Toyody? Poznaj połączenie precyzji technicznej, oddechu i dyscypliny Zen w jednym systemie treningowym.",
  "blog/linia-toyoda-germanov-jak-cwiczymy.html" => "Linia Toyoda–Germanov w praktyce: precyzja techniczna, dyscyplina wewnętrzna i odpowiedzialny przekaz instruktorski na tle innych nurtów Aikido.",
  "blog/omoiyari-uwazna-troska.html" => "Omoiyari w dojo: uważna troska o partnera, bezpieczeństwo treningu i wysoka kultura współpracy na macie.",
  "blog/jiko-sekinin-odpowiedzialnosc-osobista.html" => "Jiko sekinin w Aikido: odpowiedzialność za własny rozwój, przygotowanie, higienę techniki i postawę na treningu.",
  "blog/kuzushi-kontrolowana-nierownowaga.html" => "Kuzushi od podstaw do zastosowania: kontrolowana nierównowaga, timing i kierunek, które otwierają skuteczną technikę.",
  "en/blog.html" => "POA blog: seminar recaps, dojo updates, event announcements, and practical notes for Aikido practitioners.",
  "en/blog/bushido-way-of-the-warrior.html" => "Bushido in practical Aikido training: discipline, accountability, and dojo ethics that shape durable martial skills.",
  "en/blog/kaizen-continuous-improvement.html" => "Kaizen applied to Aikido: steady incremental improvement that compounds into reliable technical and mental progress.",
  "en/blog/gaman-endurance-and-composure.html" => "Gaman as a training principle: endurance, composure, and quality decision-making under pressure on the mat.",
  "en/blog/kintsugi-golden-repair.html" => "Kintsugi as a growth model in Aikido: learning from mistakes, repairing structure, and building resilient performance.",
  "en/blog/wabi-sabi-beauty-of-imperfection.html" => "Wabi-sabi in Aikido practice: accepting imperfection while refining movement, timing, and technical clarity.",
  "en/blog/mushin-no-mind.html" => "Mushin in partner work: developing clear, unforced responses and preserving calm precision in motion.",
  "en/blog/sesshin-deep-practice.html" => "Sesshin as deep Aikido practice: concentration, discipline, and the training standard that defines Sesshinkan Dojo.",
  "en/blog/zenshin-full-commitment.html" => "Zenshin means full commitment: body-mind unity, intent continuity, and complete execution of technique.",
  "en/blog/zanshin-awareness-after-execution.html" => "Zanshin as remaining awareness after technique: how to close action loops and preserve quality under pressure.",
  "en/blog/enso-circle-of-presence.html" => "Ensō in Aikido and Zen practice: one stroke that reveals presence, decision quality, and clean closure.",
  "en/blog/hyoshi-timing-reveals-unity-of-movement.html" => "Hyōshi in Aikido and budō: how timing reveals unity of decision, breath, and movement—and why delay breaks technique.",
  "en/blog/fudoshin-immovable-mind.html" => "Fudōshin in Aikido and budō: immovable mind as practical stability of decision, breath, and posture under pressure.",
  "en/blog/shoshin-beginners-mind.html" => "Shoshin in Aikido and budō: how beginner's mind protects training from routine, ego, and technical stagnation.",
  "en/blog/shuhari-stages-of-maturation-in-training.html" => "Shuhari in Aikido and budō: how faithful form matures into understanding and freedom without collapsing into chaos or ego.",
  "en/blog/hansei-honest-self-reflection-without-excuses.html" => "Hansei in Aikido and budō: how honest self-reflection without excuses helps practitioners see error clearly, accept correction, and mature in training.",
  "en/blog/ichi-go-ichi-e-every-encounter-happens-only-once.html" => "Ichi-go ichi-e in Aikido and budō: why every encounter, training session, and correction happens only once and deserves full presence instead of routine.",
  "en/blog/wa-harmony-without-submission.html" => "Wa in Aikido and budō: harmony without submission, and how to preserve order in relationship, correction, and shared practice under pressure.",
  "en/blog/giri-duty-without-excuses.html" => "Giri in Aikido and budō: duty without excuses as responsibility for the partner, correction, transmission line, and shared order of the dojo.",
  "en/blog/the-path-and-mastery.html" => "The Path and Mastery in budō: how mastering techniques opens the real questions, why a master says 'I know nothing', and what changes when stability does not mean closing off — in the dojo and beyond.",
  "en/blog/ikigai-the-reason-to-return-to-practice.html" => "Ikigai in Aikido and budō: why the meaning of regular practice is not a grand revelation, but something tested by returning to the mat in an ordinary week.",
  "en/blog/mottainai-do-not-waste-what-can-teach-you.html" => "Mottainai in Aikido and budō: how not to waste correction, partners, time, and energy on the mat, but turn them into real learning.",
  "en/blog/mono-no-aware-sensitivity-to-impermanence.html" => "Mono no aware in Aikido and budō: how awareness of impermanence sharpens attention, improves partner work, and clarifies decision-making instead of postponing practice.",
  "en/blog/ikkyo-the-first-teaching-that-never-ends.html" => "Ikkyo in Aikido and budō: why the first teaching remains a lifelong test of posture, center, breath, riai, and leading without force.",
  "en/blog/yugen-depth-that-cannot-be-flattened.html" => "Yūgen in Aikido and budō: how to understand the depth of technique beyond instruction — timing, distance, intent, quiet, and contact with a partner.",
  "en/blog/exams-in-budo-showing-the-road-not-performing.html" => "A budō and Aikido exam as an honest test of training, preparation, and responsibility — not a performance for the panel or a judgment of personal worth.",
  "en/blog/ukemi-falling-safely-keeping-structure-returning-to-action.html" => "Ukemi in Aikido is the art of falling safely, receiving technique, protecting the body, and returning to action with structure instead of panic.",
  "en/blog/genkikai-the-body-that-returns-to-order.html" => "Genkikai in Masatomi Ikeda's system: the third practice of Sanshinkai, giving the body a method of return after intense Aikido and Hojo training.",
  "en/blog/another-path-to-the-same-summit.html" => "Budō amid change, injury, the loss of an old rhythm, work, relationships, and everyday adversity: how not to confuse the end of one path with the end of the Path.",
  "en/blog/ninjo-human-feeling-without-losing-direction.html" => "Ninjō in Aikido and budō: how to recognize human feeling without repressing emotion or letting mood steer training instead of responsibility.",
  "en/blog/omotenashi-hospitality-that-builds-the-dojo.html" => "Omotenashi in Aikido and budō: how the quality of your attack, your openness to correction, and your conduct with less advanced partners shape dojo culture from within.",
  "en/blog/nemawashi-laying-groundwork-before-action.html" => "Nemawashi in Aikido and budō: why good technique, correction, and dojo development require groundwork before visible action.",
  "en/blog/misogi-purification-through-practice.html" => "Misogi in Aikido and budō: how clearing breath, attention, and intention strengthens technique in Toyoda’s style and remains alive in the transmission line.",
  "en/blog/five-principles-behind-every-technique.html" => "Five principles behind Aikido technique: a practical model of center, axis, timing, taking the slack out, and kuzushi together with the sub-principles that organize movement.",
  "en/blog/why-aikido-practitioners-wear-hakama.html" => "Why Aikido practitioners wear hakama: the historical logic of the garment, its link to heifuku, its effect on movement, and the symbolism of the seven pleats and seven virtues.",
  "en/blog/who-is-aikido-for.html" => "Who Aikido is really for: beginners, adults, returning practitioners, and people looking for regular training without sport competition.",
  "en/blog/is-aikido-worth-practicing.html" => "Is Aikido worth practicing? An honest answer about benefits, limits, and the kinds of goals this path serves best.",
  "en/blog/aikido-at-every-age.html" => "Aikido at every age: how to begin intelligently in your 20s, 40s, or 60s and what really determines safe long-term progress.",
  "en/blog/aikido-for-teenagers.html" => "Aikido for teenagers as a path of development: discipline, fitness, self-control, relationships, and international experience without obsession with sporting outcome.",
  "en/blog/one-teacher-one-transmission.html" => "One teacher and one coherent transmission protect students from confusion, and senior students support learning best by being good uke.",
  "en/blog/toyoda-aikido-style-technique-and-zen.html" => "What defines Fumio Toyoda’s Aikido style? Discover how technical precision, breath work, and Zen discipline form one coherent training system.",
  "en/blog/toyoda-germanov-lineage-how-we-train.html" => "Toyoda–Germanov lineage in practice: technical precision, inner discipline, and responsible instruction compared with other Aikido streams.",
  "en/blog/omoiyari-considerate-compassion.html" => "Omoiyari in the dojo: considerate compassion, partner safety, and responsible intensity in everyday training.",
  "en/blog/jiko-sekinin-personal-responsibility.html" => "Jiko sekinin in Aikido: personal responsibility for preparation, attitude, and the quality of each repetition.",
  "en/blog/kuzushi-controlled-imbalance.html" => "Kuzushi explained through practice: controlled imbalance, timing, and direction to unlock effective technique.",
}.freeze

DEFAULT_DESCRIPTIONS_PATTERNS = [
  [/\Ablog-(\d+)\.html\z/, ->(match) { "Blog POA — starsze wpisy (strona #{match[1]}): archiwalne artykuły, relacje i komentarze treningowe." }],
  [/\Aen\/blog-(\d+)\.html\z/, ->(match) { "POA blog — older posts (page #{match[1]}): archived articles, recaps, and practical dojo notes." }],
].freeze


DEFAULT_KEYWORDS = {
  "index.html" => "aikido gdynia, treningi aikido w gdyni, aikido dla początkujących gdynia, aikido trójmiasto, sztuki walki gdynia dorośli, dojo gdynia, sesshinkan dojo gdynia, poa, oskar szrajer, samoobrona gdynia",
  "" => "aikido gdynia, treningi aikido w gdyni, aikido dla początkujących gdynia, aikido trójmiasto, sztuki walki gdynia dorośli, dojo gdynia, sesshinkan dojo gdynia, poa, oskar szrajer, samoobrona gdynia",
  nil => "aikido gdynia, treningi aikido w gdyni, aikido dla początkujących gdynia, aikido trójmiasto, sztuki walki gdynia dorośli, dojo gdynia, sesshinkan dojo gdynia, poa, oskar szrajer, samoobrona gdynia",
  "en" => "Aikido Poland, Aikido Gdynia, Aikido Polish, POA, Polish Aikido Organization, Sesshinkan Dojo, Toyoda, Germanov, Oskar Szrajer, martial arts Gdynia, self-defense training, Aikido classes, dojo Gdynia",
  "en/" => "Aikido Poland, Aikido Gdynia, Aikido Polish, POA, Polish Aikido Organization, Sesshinkan Dojo, Toyoda, Germanov, Oskar Szrajer, martial arts Gdynia, self-defense training, Aikido classes, dojo Gdynia",
  "kontakt.html" => "kontakt aikido gdynia, grafik aikido gdynia, sesshinkan dojo gdynia, treningi aikido gdynia, pierwszy trening aikido gdynia, telefon dojo, adres dojo gdynia",
  "aikido/czym_jest.html" => "czym jest aikido, aikido, sztuka walki, zasady aikido, filozofia aikido, aikikai",
  "aikido/historia.html" => "historia aikido, Morihei Ueshiba, O-Sensei, rozwoj aikido, japonskie sztuki walki",
  "aikido/korzysci.html" => "korzysci aikido, samoobrona, rozwoj osobisty, sprawnosc, trening aikido",
  "aikido/dla_poczatkujacych.html" => "aikido dla początkujących gdynia, pierwszy trening aikido gdynia, podstawy aikido, dojo gdynia, trening aikido dorośli gdynia, aikido gdynia dla dorosłych",
  "aikido/aiki_taiso.html" => "aiki taiso, cwiczenia aikido, rozgrzewka, przygotowanie do treningu, koordynacja",
  "aikido/reishiki.html" => "reishiki, etykieta dojo, uklony, zasady dojo, aikido",
  "aikido/budo_zen.html" => "budo, zen, mushin, zanshin, fudoshin, bushido, cnoty samuraja, filozofia aikido",
  "aikido/ki_kokyu.html" => "ki, kokyu, kokyu-ryoku, energia życiowa, oddech w aikido, hara, seika tanden, ki no nagare",
  "slowniczek.html" => "slowniczek aikido, terminy japonskie, nazwy technik, aikido",
  "wymagania_egzaminacyjne/kyu.html" => "wymagania kyu, stopnie kyu, egzamin aikido, pasy aikido",
  "wymagania_egzaminacyjne/dan.html" => "wymagania dan, shodan, nidan, stopnie mistrzowskie, egzamin aikido",
  "lineage.html" => "linia przekazu aikido, ueshiba, toyoda, germanov, poa, tradycja",
  "biografie/o-sensei.html" => "morihei ueshiba, o-sensei, tworca aikido, biografia",
  "biografie/kisshomaru.html" => "kisshomaru ueshiba, doshu, aikido historia, biografia",
  "biografie/moriteru.html" => "moriteru ueshiba, doshu, aikido aikikai, biografia",
  "biografie/mitsuteru.html" => "mitsuteru ueshiba, waka sensei, doshu, biografia",
  "biografie/toyoda.html" => "fumio toyoda, shihan toyoda, aikido america, biografia",
  "biografie/germanov.html" => "edward germanov, shihan germanov, 7 dan, baa, biografia",
  "biografie/ostrowski.html" => "jacek ostrowski, poa, zalozyciel, biografia",
  "biografie/szrajer.html" => "oskar szrajer, poa, 5 dan, instruktor, biografia",
  "wydarzenia/2026.html" => "wydarzenia aikido 2026, seminaria, szkolenia, poa",
  "faq.html" => "faq aikido gdynia, pytania o aikido, pierwszy trening aikido gdynia, ile kosztuje aikido gdynia, strój na aikido, grafik aikido gdynia",
  "gdynia.html" => "treningi aikido w gdyni, aikido gdynia, sesshinkan dojo gdynia, aikido dla początkujących gdynia, pierwszy trening aikido gdynia, sztuki walki gdynia dorośli",
  "treningi-aikido-gdynia.html" => "treningi aikido w gdyni, zajęcia aikido gdynia, aikido gdynia grafik, sesshinkan dojo gdynia, dojo gdynia, aikido trójmiasto",
  "pierwszy-trening-aikido-gdynia.html" => "pierwszy trening aikido gdynia, jak zacząć aikido gdynia, co zabrać na aikido, aikido dla początkujących gdynia, trening próbny aikido gdynia",
  "aikido-dla-doroslych-gdynia.html" => "aikido dla dorosłych gdynia, sztuki walki gdynia dorośli, trening aikido dorośli gdynia, aikido początkujący dorośli gdynia, wieczorne treningi aikido gdynia",
  "en/contact.html" => "contact Polish Aikido Organization, Sesshinkan Dojo Gdynia, Aikido contact, training schedule, phone",
  "en/aikido/what_is.html" => "What is Aikido, Aikido principles, Ki energy, Aiki, martial arts philosophy, Japanese martial arts, Aikido training, Four Fundamental Principles, Morihei Ueshiba",
  "en/aikido/history.html" => "Aikido history, Morihei Ueshiba, O-Sensei, martial arts history, Japanese budo, Aikido development, traditional martial arts",
  "en/aikido/benefits.html" => "Aikido benefits, martial arts training, self-defense, physical fitness, mental focus, stress relief, personal development, mind-body practice",
  "en/aikido/beginners.html" => "Aikido for beginners, first Aikido class, martial arts beginners, Aikido basics, dojo etiquette, starting Aikido, beginner guide",
  "en/aikido/aiki_taiso.html" => "Aiki Taiso, Aikido exercises, warm-up exercises, martial arts conditioning, body movement, Aikido preparation, basic training",
  "en/aikido/reishiki.html" => "Reishiki, dojo etiquette, Aikido customs, martial arts respect, Japanese etiquette, bowing, dojo behavior, training protocol",
  "en/aikido/budo_zen.html" => "budo, zen, mushin, zanshin, fudoshin, bushido virtues, samurai ethics, Aikido philosophy",
  "en/aikido/ki_kokyu.html" => "Ki, Kokyu, Kokyu-ryoku, life energy, breath power, Aikido breathing, hara, seika tanden",
  "en/glossary.html" => "Aikido glossary, Japanese terms, martial arts terminology, Aikido dictionary, techniques names, ranks system, Japanese martial arts",
  "en/requirements/kyu.html" => "Kyu ranks, Aikido belts, colored belts, examination requirements, Aikido grading, beginner ranks, martial arts progression",
  "en/requirements/dan.html" => "Dan ranks, black belt, Aikido black belt, Shodan, Nidan, Sandan, Yondan, advanced requirements, master level",
  "en/biographies/o-sensei.html" => "Morihei Ueshiba, O-Sensei, Aikido founder, martial arts master, Japanese budo, Aikido creator, spiritual martial arts",
  "en/biographies/kisshomaru.html" => "Kisshomaru Ueshiba, second Doshu, Aikido development, Ueshiba family, Aikido worldwide, martial arts leadership",
  "en/biographies/moriteru.html" => "Moriteru Ueshiba, third Doshu, current Doshu, Aikido leadership, Aikikai, international Aikido, modern Aikido",
  "en/biographies/mitsuteru.html" => "Mitsuteru Ueshiba, Waka Sensei, future Doshu, Ueshiba lineage, next generation, Aikido succession",
  "en/biographies/toyoda.html" => "Fumio Toyoda, Shihan Toyoda, Aikido America, AAA founder, influential teacher, Aikido lineage, martial arts pioneer",
  "en/biographies/germanov.html" => "Edward Germanov, Shihan Germanov, 7th dan, Baltic Aikido, Tendokan, European Aikido, BAA President",
  "en/biographies/ostrowski.html" => "Jacek Ostrowski, POA founder, Polish Aikido, Aikido memorial, dedicated teacher, martial arts legacy",
  "en/biographies/szrajer.html" => "Oskar Szrajer, 5th dan, POA head, Gdynia Aikido, current instructor, Sesshinkan Dojo, Polish teacher",
  "en/lineage.html" => "Aikido lineage, martial arts lineage, Ueshiba family, Toyoda lineage, Germanov lineage, POA lineage, traditional succession",
  "en/events/2026.html" => "Aikido events 2026, seminars, workshops, training schedule, martial arts events, POA calendar, Aikido gatherings",
  "yudansha.html" => "yudansha, czarne pasy POA, Aikido instruktorzy, Shodan, Nidan, Sandan, Yondan, Godan, Dan Aikido, instruktorzy Aikido Polska, stopnie mistrzowskie, Jacek Ostrowski, Oskar Szrajer, Wojciech Korwin-Piotrowski",
  "en/yudansha.html" => "yudansha, POA black belts, Aikido instructors, Shodan, Nidan, Sandan, Yondan, Godan, Dan ranks, Aikido instructors Poland, black belt instructors, Jacek Ostrowski, Oskar Szrajer, Wojciech Korwin-Piotrowski",
  "blog.html" => "blog aikido, poa blog, seminaria aikido, dojo komunikaty, sesshinkan gdynia",
  "blog/bushido-droga-wojownika.html" => "bushido aikido, droga wojownika, etyka dojo, dyscyplina treningowa, zasady budo",
  "blog/kaizen-ciagle-doskonalenie.html" => "kaizen aikido, ciagle doskonalenie, nawyki treningowe, postep techniczny, rozwoj dojo",
  "blog/gaman-wytrwalosc.html" => "gaman aikido, wytrwalosc, opanowanie, odpornosc psychiczna, trening pod presja",
  "blog/kintsugi-zlota-naprawa.html" => "kintsugi aikido, zlota naprawa, praca z bledem, odpornosc, rozwoj osobisty",
  "blog/wabi-sabi-piekno-niedoskonalosci.html" => "wabi sabi aikido, piekno niedoskonalosci, pokora w treningu, proces doskonalenia",
  "blog/mushin-umysl-bez-umyslu.html" => "mushin aikido, umysl bez umyslu, reakcja spontaniczna, skupienie, zen w ruchu",
  "blog/sesshin-gleboka-praktyka.html" => "sesshin aikido, gleboka praktyka, intensywny trening, sesshinkan dojo, dyscyplina i skupienie",
  "blog/zenshin-pelne-zaangazowanie.html" => "zenshin aikido, pelne zaangazowanie, intencja ruchu, koncentracja, jakosc techniki",
  "blog/zanshin-czujnosc-po-technice.html" => "zanshin aikido, pozostajaca czujnosc, domkniecie techniki, uwaga po ruchu, jakosc decyzji",
  "blog/enso-krag-obecnosci.html" => "enso aikido, enso zen, zen circle, krag zen, obecność w ruchu, decyzja pod presją",
  "blog/hyoshi-rytm-timing-jednosci-ruchu.html" => "hyoshi aikido, timing aikido, rytm ruchu, ma-ai kokyu zanshin, jedność ciała i umysłu, budo",
  "blog/fudoshin-niewzruszony-umysl.html" => "fudoshin aikido, niewzruszony umysl, stabilnosc pod presja, spokoj w dzialaniu, budo, zen",
  "blog/shoshin-umysl-poczatkujacego.html" => "shoshin aikido, umysl poczatkujacego, pokora w treningu, rozwoj bez pychy, podstawy aikido, zen",
  "blog/shuhari-etapy-dojrzewania-w-treningu.html" => "shuhari aikido, etapy uczenia, dojrzewanie w treningu, shu ha ri, forma i swoboda, budo, zen",
  "blog/hansei-uczciwa-autorefleksja-bez-wymowek.html" => "hansei aikido, autorefleksja bez wymowek, uczciwa korekta, praca z bledem, rozwoj w dojo, budo, zen",
  "blog/aiki-harmonia-w-dzialaniu.html" => "aiki aikido, aiki w aikido, harmonia w dzialaniu, timing dystans balans, ma-ai kuzushi kokyu, prowadzenie ataku",
  "blog/wa-harmonia-bez-uleglosci.html" => "wa aikido, harmonia bez uleglosci, harmonia w dojo, reishiki, tori uke, korekta, budo, kultura japonska",
  "blog/giri-obowiazek-bez-wymowek.html" => "giri aikido, obowiązek w dojo, odpowiedzialność w aikido, tori uke, korekta, linia przekazu, budo, kultura japonska",
  "blog/droga-i-mistrzostwo.html" => "droga i mistrzostwo aikido, technika i zasady budo, Andre Cognard, mistrzostwo poza dojo, droga budō, shoshin, shuhari, mistrz i uczeń",
  "blog/ikigai-sens-regularnej-praktyki.html" => "ikigai aikido, ikigai, sens praktyki, regularny trening aikido, motywacja w dojo, powrót na matę, droga budo, shoshin, kultura japonska",
  "blog/mottainai-nie-marnuj-tego-co-moze-cie-nauczyc.html" => "mottainai aikido, mottainai, nie marnować korekty, błąd jako informacja, partner w aikido, energia w technice, uwaga w dojo, budo, kultura japonska",
  "blog/mono-no-aware-czulosc-wobec-przemijania.html" => "mono no aware aikido, mono no aware, przemijanie w budo, obecność na macie, nietrwałość, uważność w treningu, relacja uke tori, japonska estetyka",
  "blog/ikkyo-pierwsza-nauka-ktora-nie-konczy-sie-nigdy.html" => "ikkyo aikido, pierwsza nauka aikido, kontrola łokcia, tai sabaki, riai, centrum w aikido, ikkyo undo, postawa aikido, uke nage, budo",
  "blog/yugen-glebia-ktorej-nie-da-sie-splaszczyc.html" => "yugen aikido, yūgen, głębia techniki, wyczucie czasu aikido, maai, intencja w aikido, kontakt z partnerem, budo, japonska estetyka",
  "blog/egzamin-w-budo-pokaz-drogi-nie-wystep.html" => "egzamin w budo, egzamin aikido, stopnie aikido, budo, aikido, trening aikido, hansei, odpowiedzialność w dojo, przygotowanie do egzaminu",
  "blog/ukemi-bezpiecznie-upasc-zachowac-strukture-wrocic-do-dzialania.html" => "ukemi aikido, bezpieczne padanie, sztuka padania, aikido dla początkujących, uke i nage, jak bezpiecznie upadać, pady aikido, ukemi w życiu codziennym, budo",
  "blog/genkikai-cialo-ktore-wraca-na-miejsce.html" => "genkikai aikido, Masatomi Ikeda, Sanshinkai, Hojo, regeneracja w aikido, oddech w treningu, Michele Quaranta, Germanov, linia przekazu aikido",
  "blog/inna-sciezka-na-ten-sam-szczyt.html" => "budo zmiany i przeciwności, droga budo, zen i budo, inna ścieżka na ten sam szczyt, aikido poza dojo, praktyka codzienna, bun bu, se mu i, nieustraszoność, odpowiedzialność, życie codzienne",
  "blog/ninjo-ludzkie-uczucia-bez-utraty-kierunku.html" => "ninjo aikido, ninjō, ludzkie uczucia, emocje w treningu, giri i ninjo, odpowiedzialność w dojo, budo, kultura japonska",
  "blog/omotenashi-goscinnosc-ktora-buduje-dojo.html" => "omotenashi aikido, kultura dojo, jakość ataku uke, korekta w aikido, praca z partnerem, budo, dyscyplina na macie",
  "blog/nemawashi-przygotowanie-gruntu-przed-dzialaniem.html" => "nemawashi aikido, przygotowanie gruntu, korekta w aikido, rozwój dojo, zmiana w dojo, budo, kultura japonska",
  "blog/misogi-oczyszczenie-przez-praktyke.html" => "misogi, misogi aikido, toyoda misogi, oczyszczenie w budo, zen i aikido, linia toyoda germanov",
  "blog/5-zasad-kazdej-techniki.html" => "5 zasad techniki aikido, centrum os timing, wybranie luzu, kuzushi, budo bushido, hara, os ciala, ma-ai, hyoshi",
  "blog/dlaczego-w-aikido-nosi-sie-hakame.html" => "hakama aikido, dlaczego nosi się hakamę, heifuku, 7 plis hakamy, cnoty samuraja, bushido aikido, strój aikido",
  "blog/dla-kogo-jest-aikido.html" => "dla kogo jest aikido, aikido dla początkujących, aikido dla dorosłych, kto może trenować aikido, trening aikido gdynia",
  "blog/czy-warto-cwiczyc-aikido.html" => "czy warto ćwiczyć aikido, korzyści z aikido, trening aikido dla dorosłych, czy aikido ma sens, aikido gdynia",
  "blog/aikido-w-kazdym-wieku.html" => "aikido w każdym wieku, czy można zacząć aikido po 40, aikido po 50, aikido dla dorosłych, pierwszy trening aikido",
  "blog/aikido-dla-nastolatkow.html" => "aikido dla nastolatków, aikido młodzież, sztuki walki dla nastolatków, rozwój nastolatka sport, dyscyplina i samokontrola młodzieży, aikido gdynia",
  "blog/ichi-go-ichi-e-kazde-spotkanie-zdarza-sie-tylko-raz.html" => "ichi go ichi e aikido, kazde spotkanie zdarza sie tylko raz, obecnosc w treningu, uwaga w dojo, seminaria aikido, budo, zen",
  "blog/jeden-nauczyciel-jeden-przekaz.html" => "jeden nauczyciel jeden przekaz, aikido nauczanie, metodyka dojo, seminarium aikido, uke, shuhari, przekaz szkoły",
  "blog/styl-aikido-fumio-toyody-technika-i-zen.html" => "styl aikido toyody, fumio toyoda, aikido zen, misogi, trening budo, linia toyoda",
  "blog/linia-toyoda-germanov-jak-cwiczymy.html" => "linia toyoda germanov, aikido germanov, metodyka aikido, budo praktyka, aikido szkoła",
  "blog/omoiyari-uwazna-troska.html" => "omoiyari aikido, uwazna troska, partnering, bezpieczenstwo na macie, kultura dojo",
  "blog/jiko-sekinin-odpowiedzialnosc-osobista.html" => "jiko sekinin aikido, odpowiedzialnosc osobista, samodyscyplina, etyka treningu",
  "blog/kuzushi-kontrolowana-nierownowaga.html" => "kuzushi aikido, kontrolowana nierownowaga, balans, timing, prowadzenie partnera",
  "en/blog.html" => "aikido blog, poa updates, dojo announcements, seminar recap, sesshinkan",
  "en/blog/bushido-way-of-the-warrior.html" => "bushido aikido, warrior way, dojo ethics, training discipline, budo principles",
  "en/blog/kaizen-continuous-improvement.html" => "kaizen aikido, continuous improvement, training habits, technical progression, dojo growth",
  "en/blog/gaman-endurance-and-composure.html" => "gaman aikido, endurance, composure, resilience, pressure training",
  "en/blog/kintsugi-golden-repair.html" => "kintsugi aikido, golden repair, learning from mistakes, resilience, mindset",
  "en/blog/wabi-sabi-beauty-of-imperfection.html" => "wabi sabi aikido, beauty of imperfection, humility, long-term training process",
  "en/blog/mushin-no-mind.html" => "mushin aikido, no mind, spontaneous response, calm focus, zen in movement",
  "en/blog/sesshin-deep-practice.html" => "sesshin aikido, deep practice, intensive training, sesshinkan dojo, discipline and focus",
  "en/blog/zenshin-full-commitment.html" => "zenshin aikido, full commitment, intent continuity, concentration, execution quality",
  "en/blog/zanshin-awareness-after-execution.html" => "zanshin aikido, remaining awareness, follow-through, post-execution control, decision quality",
  "en/blog/enso-circle-of-presence.html" => "enso aikido, enso zen, zen circle, presence in motion, decision under pressure, clean execution",
  "en/blog/hyoshi-timing-reveals-unity-of-movement.html" => "hyoshi aikido, aikido timing, rhythm in movement, ma-ai kokyu zanshin, body-mind unity, budo",
  "en/blog/fudoshin-immovable-mind.html" => "fudoshin aikido, immovable mind, stability under pressure, calm action, budo, zen",
  "en/blog/shoshin-beginners-mind.html" => "shoshin aikido, beginner's mind, humility in training, growth without ego, aikido fundamentals, zen",
  "en/blog/shuhari-stages-of-maturation-in-training.html" => "shuhari aikido, stages of learning, maturation in training, shu ha ri, form and freedom, budo, zen",
  "en/blog/hansei-honest-self-reflection-without-excuses.html" => "hansei aikido, honest self-reflection, training correction, working with error, dojo growth, budo, zen",
  "en/blog/ichi-go-ichi-e-every-encounter-happens-only-once.html" => "ichi go ichi e aikido, every encounter happens only once, presence in training, dojo attention, aikido seminars, budo, zen",
  "en/blog/wa-harmony-without-submission.html" => "wa aikido, harmony without submission, dojo harmony, reishiki, tori uke, correction, budo, Japanese culture",
  "en/blog/giri-duty-without-excuses.html" => "giri aikido, duty in the dojo, responsibility in aikido, tori uke, correction, transmission line, budo, Japanese culture",
  "en/blog/the-path-and-mastery.html" => "path and mastery aikido, technique and principles budo, Andre Cognard, mastery beyond dojo, budo path, shoshin, shuhari, master and student",
  "en/blog/ikigai-the-reason-to-return-to-practice.html" => "ikigai aikido, ikigai, meaning of practice, regular aikido training, dojo motivation, return to the mat, budo path, shoshin, Japanese culture",
  "en/blog/mottainai-do-not-waste-what-can-teach-you.html" => "mottainai aikido, mottainai, do not waste correction, dojo attention, aikido partner, energy in technique, budo, Japanese culture",
  "en/blog/mono-no-aware-sensitivity-to-impermanence.html" => "mono no aware aikido, mono no aware, impermanence in budo, presence on the mat, transient beauty, uke tori relation, dojo awareness, Japanese aesthetics",
  "en/blog/ikkyo-the-first-teaching-that-never-ends.html" => "ikkyo aikido, first teaching aikido, elbow control, tai sabaki, riai, aikido center, ikkyo undo, aikido posture, uke nage, budo",
  "en/blog/yugen-depth-that-cannot-be-flattened.html" => "yugen aikido, yūgen, depth of technique, aikido timing, maai, intent in aikido, partner contact, budo, Japanese aesthetics",
  "en/blog/exams-in-budo-showing-the-road-not-performing.html" => "budo exam, aikido grading, aikido exam, martial arts grading, budo, aikido training, hansei, dojo responsibility, preparing for grading",
  "en/blog/ukemi-falling-safely-keeping-structure-returning-to-action.html" => "ukemi aikido, safe falling, breakfall aikido, aikido beginners, uke and nage, martial arts falling, ukemi in daily life, budo",
  "en/blog/genkikai-the-body-that-returns-to-order.html" => "genkikai aikido, Masatomi Ikeda, Sanshinkai, Hojo, recovery in aikido, breath in training, Michele Quaranta, Germanov, aikido transmission line",
  "en/blog/another-path-to-the-same-summit.html" => "budo change and adversity, budo path, zen and budo, another path to the same summit, aikido beyond the dojo, daily practice, bun bu, se mu i, fearlessness, responsibility, everyday life",
  "en/blog/ninjo-human-feeling-without-losing-direction.html" => "ninjo aikido, ninjō, human feeling, emotions in training, giri and ninjo, responsibility in dojo, budo, Japanese culture",
  "en/blog/omotenashi-hospitality-that-builds-the-dojo.html" => "omotenashi aikido, dojo culture, uke attack quality, receiving correction, partner work, budo, mat discipline",
  "en/blog/nemawashi-laying-groundwork-before-action.html" => "nemawashi aikido, laying groundwork, aikido correction, dojo development, change in the dojo, budo, Japanese culture",
  "en/blog/misogi-purification-through-practice.html" => "misogi, misogi aikido, toyoda misogi, purification in budo, zen and aikido, toyoda germanov lineage",
  "en/blog/five-principles-behind-every-technique.html" => "five principles aikido technique, center axis timing, slack removal, kuzushi, budo bushido, hara, ma-ai, hyoshi",
  "en/blog/why-aikido-practitioners-wear-hakama.html" => "hakama aikido, why wear hakama in aikido, heifuku, seven pleats hakama, samurai virtues, bushido aikido, aikido uniform",
  "en/blog/who-is-aikido-for.html" => "who is aikido for, aikido for beginners, aikido for adults, who can train aikido, aikido training gdynia",
  "en/blog/is-aikido-worth-practicing.html" => "is aikido worth practicing, aikido benefits, aikido training for adults, is aikido useful, aikido gdynia",
  "en/blog/aikido-at-every-age.html" => "aikido at every age, can you start aikido after 40, aikido after 50, aikido for adults, first aikido class",
  "en/blog/aikido-for-teenagers.html" => "aikido for teenagers, teen martial arts, youth aikido, discipline for teens, self-control and confidence for teenagers, aikido gdynia",
  "en/blog/one-teacher-one-transmission.html" => "one teacher one transmission, aikido teaching, dojo pedagogy, aikido seminar, uke, shuhari, school transmission",
  "en/blog/toyoda-aikido-style-technique-and-zen.html" => "toyoda aikido style, fumio toyoda, aikido zen, misogi, budo training, toyoda lineage",
  "en/blog/toyoda-germanov-lineage-how-we-train.html" => "toyoda germanov lineage, germanov aikido, aikido methodology, budo practice, aikido school",
  "en/blog/omoiyari-considerate-compassion.html" => "omoiyari aikido, considerate compassion, partner safety, cooperative training, dojo culture",
  "en/blog/jiko-sekinin-personal-responsibility.html" => "jiko sekinin aikido, personal responsibility, self-discipline, training ethics",
  "en/blog/kuzushi-controlled-imbalance.html" => "kuzushi aikido, controlled imbalance, timing, direction, partner guidance",
}.freeze

DEFAULT_KEYWORDS_PATTERNS = [
  [/\Ablog-(\d+)\.html\z/, ->(match) { "blog aikido archiwum, starsze wpisy poa, artykuly dojo, aikido gdynia" }],
  [/\Aen\/blog-(\d+)\.html\z/, ->(match) { "aikido blog archive, older posts, dojo articles, poa updates" }],
].freeze


ARTICLE_SCHEMA_DATA = {
  "blog/enso-krag-obecnosci.html" => {
    name: "Ensō — krąg obecności i trening decyzji",
    lang: "pl",
    date_published: "2026-03-06",
    date_modified: "2026-03-06",
  },
  "en/blog/enso-circle-of-presence.html" => {
    name: "Ensō — circle of presence and decision training",
    lang: "en",
    date_published: "2026-03-06",
    date_modified: "2026-03-06",
  },
  "blog/hyoshi-rytm-timing-jednosci-ruchu.html" => {
    name: "Hyōshi — rytm i timing jedności w Aikido",
    lang: "pl",
    date_published: "2026-03-06",
    date_modified: "2026-03-06",
  },
  "en/blog/hyoshi-timing-reveals-unity-of-movement.html" => {
    name: "Hyōshi — rhythm and timing of unity in Aikido",
    lang: "en",
    date_published: "2026-03-06",
    date_modified: "2026-03-06",
  },
  "blog/fudoshin-niewzruszony-umysl.html" => {
    name: "Fudōshin — niewzruszony umysł i stabilność pod presją",
    lang: "pl",
    date_published: "2026-03-14",
    date_modified: "2026-03-14",
  },
  "blog/shoshin-umysl-poczatkujacego.html" => {
    name: "Shoshin — umysł początkującego i pokora w rozwoju",
    lang: "pl",
    date_published: "2026-03-15",
    date_modified: "2026-03-15",
  },
  "blog/shuhari-etapy-dojrzewania-w-treningu.html" => {
    name: "Shuhari — etapy dojrzewania w treningu i droga do swobody",
    lang: "pl",
    date_published: "2026-03-18",
    date_modified: "2026-03-18",
  },
  "blog/hansei-uczciwa-autorefleksja-bez-wymowek.html" => {
    name: "Hansei — uczciwa autorefleksja bez wymówek",
    lang: "pl",
    date_published: "2026-03-26",
    date_modified: "2026-03-26",
  },
  "blog/aiki-harmonia-w-dzialaniu.html" => {
    name: "Aiki — harmonia w działaniu, nie w deklaracji",
    lang: "pl",
    date_published: "2026-04-02",
    date_modified: "2026-04-02",
  },
  "blog/wa-harmonia-bez-uleglosci.html" => {
    name: "Wa — harmonia bez uległości",
    lang: "pl",
    date_published: "2026-04-25",
    date_modified: "2026-04-25",
  },
  "blog/giri-obowiazek-bez-wymowek.html" => {
    name: "Giri — obowiązek bez wymówek",
    lang: "pl",
    date_published: "2026-04-28",
    date_modified: "2026-04-28",
  },
  "blog/droga-i-mistrzostwo.html" => {
    name: "Droga i mistrzostwo",
    lang: "pl",
    date_published: "2026-05-18",
    date_modified: "2026-05-18",
  },
  "blog/ikigai-sens-regularnej-praktyki.html" => {
    name: "Ikigai — sens, który wytrzymuje zwykły tydzień",
    lang: "pl",
    date_published: "2026-05-25",
    date_modified: "2026-05-25",
  },
  "blog/mottainai-nie-marnuj-tego-co-moze-cie-nauczyc.html" => {
    name: "Mottainai — nie marnuj tego, z czego możesz się uczyć",
    lang: "pl",
    date_published: "2026-05-22",
    date_modified: "2026-05-22",
  },
  "blog/mono-no-aware-czulosc-wobec-przemijania.html" => {
    name: "Mono no aware — czułość wobec przemijania, która porządkuje praktykę",
    lang: "pl",
    date_published: "2026-05-30",
    date_modified: "2026-05-30",
  },
  "blog/ikkyo-pierwsza-nauka-ktora-nie-konczy-sie-nigdy.html" => {
    name: "Ikkyo — pierwsza nauka, która nie kończy się nigdy",
    lang: "pl",
    date_published: "2026-05-31",
    date_modified: "2026-05-31",
  },
  "blog/yugen-glebia-ktorej-nie-da-sie-splaszczyc.html" => {
    name: "Yūgen — głębia, której nie da się spłaszczyć do instrukcji",
    lang: "pl",
    date_published: "2026-06-03",
    date_modified: "2026-06-03",
  },
  "blog/egzamin-w-budo-pokaz-drogi-nie-wystep.html" => {
    name: "Egzamin w budō — pokaz drogi, nie występ przed komisją",
    lang: "pl",
    date_published: "2026-06-13",
    date_modified: "2026-06-13",
  },
  "blog/ukemi-bezpiecznie-upasc-zachowac-strukture-wrocic-do-dzialania.html" => {
    name: "Ukemi — jak bezpiecznie upadać i wracać do działania",
    lang: "pl",
    date_published: "2026-06-11",
    date_modified: "2026-06-11",
  },
  "blog/genkikai-cialo-ktore-wraca-na-miejsce.html" => {
    name: "Genkikai — ciało, które wraca na miejsce",
    lang: "pl",
    date_published: "2026-06-08",
    date_modified: "2026-06-08",
  },
  "blog/inna-sciezka-na-ten-sam-szczyt.html" => {
    name: "Inna ścieżka na ten sam szczyt — budō wobec zmian i przeciwności",
    lang: "pl",
    date_published: "2026-06-04",
    date_modified: "2026-06-04",
  },
  "blog/ninjo-ludzkie-uczucia-bez-utraty-kierunku.html" => {
    name: "Ninjō — ludzkie uczucia bez utraty kierunku",
    lang: "pl",
    date_published: "2026-05-01",
    date_modified: "2026-05-01",
  },
  "blog/omotenashi-goscinnosc-ktora-buduje-dojo.html" => {
    name: "Omotenashi — gościnność, która buduje dojo",
    lang: "pl",
    date_published: "2026-05-09",
    date_modified: "2026-05-09",
  },
  "blog/nemawashi-przygotowanie-gruntu-przed-dzialaniem.html" => {
    name: "Nemawashi — przygotowanie gruntu przed działaniem",
    lang: "pl",
    date_published: "2026-05-16",
    date_modified: "2026-05-16",
  },
  "blog/misogi-oczyszczenie-przez-praktyke.html" => {
    name: "Misogi — oczyszczenie przez praktykę",
    lang: "pl",
    date_published: "2026-04-04",
    date_modified: "2026-04-04",
  },
  "blog/5-zasad-kazdej-techniki.html" => {
    name: "5 zasad każdej techniki — centrum, oś, timing, wybranie luzu, kuzushi",
    lang: "pl",
    date_published: "2026-04-11",
    date_modified: "2026-04-11",
  },
  "blog/dlaczego-w-aikido-nosi-sie-hakame.html" => {
    name: "Dlaczego w aikido nosi się hakamę?",
    lang: "pl",
    date_published: "2026-04-16",
    date_modified: "2026-04-16",
  },
  "blog/dla-kogo-jest-aikido.html" => {
    name: "Dla kogo jest aikido?",
    lang: "pl",
    date_published: "2026-04-20",
    date_modified: "2026-04-20",
  },
  "blog/czy-warto-cwiczyc-aikido.html" => {
    name: "Czy warto ćwiczyć aikido?",
    lang: "pl",
    date_published: "2026-04-20",
    date_modified: "2026-04-20",
  },
  "blog/aikido-w-kazdym-wieku.html" => {
    name: "Aikido w każdym wieku",
    lang: "pl",
    date_published: "2026-04-20",
    date_modified: "2026-04-20",
  },
  "blog/aikido-dla-nastolatkow.html" => {
    name: "Aikido dla nastolatków",
    lang: "pl",
    date_published: "2026-04-20",
    date_modified: "2026-04-20",
  },
  "blog/ichi-go-ichi-e-kazde-spotkanie-zdarza-sie-tylko-raz.html" => {
    name: "Ichi-go ichi-e — każde spotkanie zdarza się tylko raz",
    lang: "pl",
    date_published: "2026-03-26",
    date_modified: "2026-03-26",
  },
  "blog/jeden-nauczyciel-jeden-przekaz.html" => {
    name: "Jeden nauczyciel, jeden przekaz — porządek nauki w dojo i na seminarium",
    lang: "pl",
    date_published: "2026-03-18",
    date_modified: "2026-03-18",
  },
  "en/blog/fudoshin-immovable-mind.html" => {
    name: "Fudōshin — immovable mind and stability under pressure",
    lang: "en",
    date_published: "2026-03-14",
    date_modified: "2026-03-14",
  },
  "en/blog/shoshin-beginners-mind.html" => {
    name: "Shoshin — beginner's mind and humility in growth",
    lang: "en",
    date_published: "2026-03-15",
    date_modified: "2026-03-15",
  },
  "en/blog/shuhari-stages-of-maturation-in-training.html" => {
    name: "Shuhari — stages of maturation in training and the path to freedom",
    lang: "en",
    date_published: "2026-03-18",
    date_modified: "2026-03-18",
  },
  "en/blog/hansei-honest-self-reflection-without-excuses.html" => {
    name: "Hansei — honest self-reflection without excuses",
    lang: "en",
    date_published: "2026-03-26",
    date_modified: "2026-03-26",
  },
  "en/blog/aiki-harmony-in-action.html" => {
    name: "Aiki — harmony in action, not in slogans",
    lang: "en",
    date_published: "2026-04-02",
    date_modified: "2026-04-02",
  },
  "en/blog/wa-harmony-without-submission.html" => {
    name: "Wa — harmony without submission",
    lang: "en",
    date_published: "2026-04-25",
    date_modified: "2026-04-25",
  },
  "en/blog/giri-duty-without-excuses.html" => {
    name: "Giri — duty without excuses",
    lang: "en",
    date_published: "2026-04-28",
    date_modified: "2026-04-28",
  },
  "en/blog/the-path-and-mastery.html" => {
    name: "The Path and Mastery",
    lang: "en",
    date_published: "2026-05-18",
    date_modified: "2026-05-18",
  },
  "en/blog/ikigai-the-reason-to-return-to-practice.html" => {
    name: "Ikigai — meaning that survives an ordinary week",
    lang: "en",
    date_published: "2026-05-25",
    date_modified: "2026-05-25",
  },
  "en/blog/mottainai-do-not-waste-what-can-teach-you.html" => {
    name: "Mottainai — do not waste what can teach you",
    lang: "en",
    date_published: "2026-05-22",
    date_modified: "2026-05-22",
  },
  "en/blog/mono-no-aware-sensitivity-to-impermanence.html" => {
    name: "Mono no aware — sensitivity to impermanence that sharpens practice",
    lang: "en",
    date_published: "2026-05-30",
    date_modified: "2026-05-30",
  },
  "en/blog/ikkyo-the-first-teaching-that-never-ends.html" => {
    name: "Ikkyo — the first teaching that never ends",
    lang: "en",
    date_published: "2026-05-31",
    date_modified: "2026-05-31",
  },
  "en/blog/yugen-depth-that-cannot-be-flattened.html" => {
    name: "Yūgen — depth that cannot be flattened into instruction",
    lang: "en",
    date_published: "2026-06-03",
    date_modified: "2026-06-03",
  },
  "en/blog/exams-in-budo-showing-the-road-not-performing.html" => {
    name: "Exams in Budō — showing the road, not performing for the panel",
    lang: "en",
    date_published: "2026-06-13",
    date_modified: "2026-06-13",
  },
  "en/blog/ukemi-falling-safely-keeping-structure-returning-to-action.html" => {
    name: "Ukemi — falling safely, keeping structure, returning to action",
    lang: "en",
    date_published: "2026-06-11",
    date_modified: "2026-06-11",
  },
  "en/blog/genkikai-the-body-that-returns-to-order.html" => {
    name: "Genkikai — the body that returns to order",
    lang: "en",
    date_published: "2026-06-08",
    date_modified: "2026-06-08",
  },
  "en/blog/another-path-to-the-same-summit.html" => {
    name: "Another path to the same summit — budō amid change and adversity",
    lang: "en",
    date_published: "2026-06-04",
    date_modified: "2026-06-04",
  },
  "en/blog/ninjo-human-feeling-without-losing-direction.html" => {
    name: "Ninjō — human feeling without losing direction",
    lang: "en",
    date_published: "2026-05-01",
    date_modified: "2026-05-01",
  },
  "en/blog/omotenashi-hospitality-that-builds-the-dojo.html" => {
    name: "Omotenashi — hospitality that builds the dojo",
    lang: "en",
    date_published: "2026-05-09",
    date_modified: "2026-05-09",
  },
  "en/blog/nemawashi-laying-groundwork-before-action.html" => {
    name: "Nemawashi — laying the groundwork before action",
    lang: "en",
    date_published: "2026-05-16",
    date_modified: "2026-05-16",
  },
  "en/blog/misogi-purification-through-practice.html" => {
    name: "Misogi — purification through practice",
    lang: "en",
    date_published: "2026-04-04",
    date_modified: "2026-04-04",
  },
  "en/blog/five-principles-behind-every-technique.html" => {
    name: "Five principles behind every technique — center, axis, timing, slack removal, kuzushi",
    lang: "en",
    date_published: "2026-04-11",
    date_modified: "2026-04-11",
  },
  "en/blog/why-aikido-practitioners-wear-hakama.html" => {
    name: "Why do Aikido practitioners wear hakama?",
    lang: "en",
    date_published: "2026-04-16",
    date_modified: "2026-04-16",
  },
  "en/blog/who-is-aikido-for.html" => {
    name: "Who is Aikido for?",
    lang: "en",
    date_published: "2026-04-20",
    date_modified: "2026-04-20",
  },
  "en/blog/is-aikido-worth-practicing.html" => {
    name: "Is Aikido worth practicing?",
    lang: "en",
    date_published: "2026-04-20",
    date_modified: "2026-04-20",
  },
  "en/blog/aikido-at-every-age.html" => {
    name: "Aikido at every age",
    lang: "en",
    date_published: "2026-04-20",
    date_modified: "2026-04-20",
  },
  "en/blog/aikido-for-teenagers.html" => {
    name: "Aikido for teenagers",
    lang: "en",
    date_published: "2026-04-20",
    date_modified: "2026-04-20",
  },
  "en/blog/ichi-go-ichi-e-every-encounter-happens-only-once.html" => {
    name: "Ichi-go ichi-e — every encounter happens only once",
    lang: "en",
    date_published: "2026-03-26",
    date_modified: "2026-03-26",
  },
  "en/blog/one-teacher-one-transmission.html" => {
    name: "One teacher, one transmission — order in dojo and seminar learning",
    lang: "en",
    date_published: "2026-03-18",
    date_modified: "2026-03-18",
  },
  # --- Bugfix (t_cd94c6bf): older posts lacked Article JSON-LD. Names
  # follow the existing convention (default page title without the
  # " | Blog" suffix); dates come from the BLOG_POSTS entries. ---
  "blog/bushido-droga-wojownika.html" => {
    name: "Bushido — droga wojownika w praktyce dojo",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/kaizen-ciagle-doskonalenie.html" => {
    name: "Kaizen — ciągłe doskonalenie w Aikido",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/gaman-wytrwalosc.html" => {
    name: "Gaman — wytrwałość i opanowanie na macie",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/kintsugi-zlota-naprawa.html" => {
    name: "Kintsugi — złota naprawa i odporność psychiczna",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/wabi-sabi-piekno-niedoskonalosci.html" => {
    name: "Wabi-sabi — piękno niedoskonałości w treningu",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/mushin-umysl-bez-umyslu.html" => {
    name: "Mushin — umysł bez umysłu w Aikido",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/zenshin-pelne-zaangazowanie.html" => {
    name: "Zenshin — pełne zaangażowanie w każdym ruchu",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/omoiyari-uwazna-troska.html" => {
    name: "Omoiyari — uważna troska i odpowiedzialny partnering",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/jiko-sekinin-odpowiedzialnosc-osobista.html" => {
    name: "Jiko sekinin — odpowiedzialność osobista w dojo",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/kuzushi-kontrolowana-nierownowaga.html" => {
    name: "Kuzushi — kontrolowana nierównowaga i prowadzenie techniki",
    lang: "pl",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "blog/sesshin-gleboka-praktyka.html" => {
    name: "Sesshin — głęboka praktyka i tożsamość Sesshinkan Dojo",
    lang: "pl",
    date_published: "2026-02-24",
    date_modified: "2026-02-24",
  },
  "blog/zanshin-czujnosc-po-technice.html" => {
    name: "Zanshin — czujność po technice i domknięcie działania",
    lang: "pl",
    date_published: "2026-02-25",
    date_modified: "2026-02-25",
  },
  "blog/styl-aikido-fumio-toyody-technika-i-zen.html" => {
    name: "Styl Aikido Fumio Toyody — technika i Zen jako jeden system",
    lang: "pl",
    date_published: "2026-03-07",
    date_modified: "2026-03-07",
  },
  "blog/linia-toyoda-germanov-jak-cwiczymy.html" => {
    name: "Linia Toyoda–Germanov — jak ćwiczymy i czym wyróżnia się nasza szkoła",
    lang: "pl",
    date_published: "2026-03-07",
    date_modified: "2026-03-07",
  },
  "en/blog/bushido-way-of-the-warrior.html" => {
    name: "Bushido — the warrior's way in dojo practice",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/kaizen-continuous-improvement.html" => {
    name: "Kaizen — continuous improvement in Aikido training",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/gaman-endurance-and-composure.html" => {
    name: "Gaman — endurance and composure on the mat",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/kintsugi-golden-repair.html" => {
    name: "Kintsugi — golden repair and resilient mindset",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/wabi-sabi-beauty-of-imperfection.html" => {
    name: "Wabi-sabi — beauty of imperfection in practice",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/mushin-no-mind.html" => {
    name: "Mushin — no-mind state in Aikido practice",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/zenshin-full-commitment.html" => {
    name: "Zenshin — full commitment in every movement",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/omoiyari-considerate-compassion.html" => {
    name: "Omoiyari — considerate compassion in partner work",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/jiko-sekinin-personal-responsibility.html" => {
    name: "Jiko sekinin — personal responsibility in the dojo",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/kuzushi-controlled-imbalance.html" => {
    name: "Kuzushi — controlled imbalance and technical guidance",
    lang: "en",
    date_published: "2026-02-23",
    date_modified: "2026-02-23",
  },
  "en/blog/sesshin-deep-practice.html" => {
    name: "Sesshin — deep practice and Sesshinkan Dojo identity",
    lang: "en",
    date_published: "2026-02-24",
    date_modified: "2026-02-24",
  },
  "en/blog/zanshin-awareness-after-execution.html" => {
    name: "Zanshin — awareness after execution and process closure",
    lang: "en",
    date_published: "2026-02-25",
    date_modified: "2026-02-25",
  },
  "en/blog/toyoda-aikido-style-technique-and-zen.html" => {
    name: "Fumio Toyoda’s Aikido style — technique and Zen as one system",
    lang: "en",
    date_published: "2026-03-07",
    date_modified: "2026-03-07",
  },
  "en/blog/toyoda-germanov-lineage-how-we-train.html" => {
    name: "Toyoda–Germanov lineage — how we train and what sets our school apart",
    lang: "en",
    date_published: "2026-03-07",
    date_modified: "2026-03-07",
  },
}.freeze
    end
  end
end
